//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUPortal.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SheduledEvent> SheduledEvents { get; set; }
        public virtual DbSet<Courses> Courses1 { get; set; }
        public virtual DbSet<Quarters> Quarters { get; set; }
        public virtual DbSet<Years> Years { get; set; }
        public virtual DbSet<Sprint> Sprints { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Person> People { get; set; }
    }
}
